### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by xsuchy** [lericson/procname#3]
Can you please add support for python3. When I use it with python3 I get:

```
Failed example:
    import procname
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib64/python3.3/doctest.py", line 1287, in __run
        compileflags, 1), test.globs)
      File "<doctest __main__[0]>", line 1, in <module>
        import procname
    ImportError: /home/msuchy/rpmbuild/BUILDROOT/python-procname-0.3-2.git.2.190158a.fc19.x86_64/usr/lib64/python3.3/site-packages/procname.cpython-33m.so: undefined symbol: Py_InitModule3
```

**Comment by lericson** [comment]
Will you pay me in bitcoin?

**Comment by xsuchy** [comment]
No :) I find you package interesting and wanted to package it for Fedora and get it there. But without python3 it is half of fun.

**Comment by lericson** [comment]
I see friend,

I cannot however dispense many minutes on this right now.

-Ludvig

**Comment by xsuchy** [comment]
Fair enough. I will try to create PR in upcoming weeks.
